### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by tharunc** [ssg8288/Surviellance-Bomb-Diffusion-Robot#12]
Hello there,
    I would like to work on the readme.md. Kindly assign it to me.

**Comment by ssg8288** [comment]
> 
> 
> Hello there,
> I would like to work on the readme.md. Kindly assign it to me.

What work would you like to contribute in its readme kindly, state @tharunc

**Comment by ssg8288** [comment]
> 
> 
> > Hello there,
> > I would like to work on the readme.md. Kindly assign it to me.
> 
> What work would you like to contribute in its readme kindly, state @tharunc

are you willing to work on the issue then kindly tell me what would you like to update n the readme file or else have to close this issue

**Comment by ssg8288** [comment]
since, there is no response I'm closing this issue..
